### ISSUE TITLE
Release Date?

### ISSUE THREAD

**Issue by drdh** [Fu-Dayuan/PreAct#1]
Hi, I was wondering if you had any idea when it might be ready to be open-sourced. Thanks!

**Comment by lcl101** [comment]
同问

**Comment by Fu-Dayuan** [comment]
> 同问

the same as [https://github.com/Fu-Dayuan/PreAct/issues/2](url)
we will release our code after blind review (including PreAct+TOT in the new version)

**Comment by Fu-Dayuan** [comment]
Thank you for your attention~ We have now open-sourced the experiment with Preact + TOT. After organizing the code, we will also continue to open-source the experiments with Peract on AgentBench!
