### ISSUE TITLE
什么时候开源？

### ISSUE THREAD

**Issue by LightningLeader** [Fu-Dayuan/PreAct#2]
你好，请问什么时候开源？
不会要一直挂着空仓库吧。。我看还是北邮AI院的组，应该不会吧。

**Comment by Fu-Dayuan** [comment]
抱歉之前没看GitHub。我们目前论文还没中稿，目前还在扩充实验中（我现在就在补preact+tot的实验）。我们会在中稿后第一时间开源

**Comment by LightningLeader** [comment]
> 抱歉之前没看GitHub。我们目前论文还没中稿，目前还在扩充实验中（我现在就在补preact+tot的实验）。我们会在中稿后第一时间开源

🆗，明白了。那麻烦你把我这个issue给删除吧。

**Comment by Fu-Dayuan** [comment]
感谢你的关注~我们现在开源了preact+tot的实验，后续整理完代码后也会继续开源peract在AgentBench上的实验！
